version: '3.3'
name: flashxdocker # This field requires docker-compose V2, docker-desktop V4 | name must be lower case, ex: flashxdocker
services:
  postgres:
    image: postgres:12
    container_name: postgres-12
    restart: unless-stopped # Ignore using restart: always to save resource
    environment:
      - POSTGRES_USER=flash
      - POSTGRES_PASSWORD=12345678
    ports:
      - '5432:5432'
    volumes: 
      - D:/AppData/Docker/Postgres:/var/lib/postgresql/data
  mysql:
    image: mysql:8.0
    container_name: mysql-8
    # cap_add:
    #   - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password # Allow authen with native password for legacy system
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=mysqldb
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=flash # Must Grant All DBA Privileges (Except: Usage) and Schema Privilages (% All - Table Privilages + Other Privilages) to MAKE THIS USER LIKE ROOT
      - MYSQL_PASSWORD=12345678
    ports:
      - '3306:3306'
    volumes:
      - D:/AppData/Docker/MySQL:/var/lib/mysql
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # Not sure
  
  rabbitmq:
    image: rabbitmq:3.11-management # Using xx-management tag to have built-in UI management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=flash # Default system user/pass is guest/guest
      - RABBITMQ_DEFAULT_PASS=12345678
    ports:
      - '5672:5672' # AMQP protocol port
      - '15672:15672' # HTTP management UI
    volumes:
      - D:/AppData/Docker/RabbitMQ:/var/lib/rabbitmq

  ibmmq:
    image: ibmcom/mq:9.2.0.0-r1 # 9.2.2.0-r1 Error when restarting web service
    container_name: ibmmq
    restart: unless-stopped
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
    ports:
      - "1414:1414"
      - "9443:9443"
    volumes:
      - D:/AppData/Docker/IBMMQ:/var/mqm
    stdin_open: true
    tty: true
    # hostname: mq

  redis: # Execute Redis CLI: docker exec -it redis redis-cli
    image: redis:7.0
    container_name: redis
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - D:/AppData/Docker/Redis:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.3
    restart: unless-stopped # Default for this service is: on-failure -> Using unless-stopped to save resource
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.2.3
    restart: unless-stopped # Default for this service is: on-failure -> Using unless-stopped to save resource
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    
volumes:
  flashxdocker:
    driver: local
